-- TASKS
-- 1.Show all customers.
-- 2. Show customers from Canada.
-- 3.Show all products costing more than $50.
-- 4.Show products in the Electronics category.
-- 5.Display the 10 most expensive products.
-- 6.Show all completed orders.
-- 7.Show customers who signed up after January 1, 2025.
-- 8.Show each order with: customer name, order(id,date,status)
-- 9. Show every product that has been ordered (product name, category, quantity ordered)
-- 10. Show all customers and their orders, including customers who have never placed an order.
-- 11. Show each order with :( customer name, product name, quantity, price) 
-- 12. Calculate the revenue generated by each order item.
-- 13. Calculate the total revenue generated by the store.
-- 14. Calculate total revenue for each product.
-- 15. Calculate total quantity sold for each product.
-- 16. Find the top 10 best-selling products based on quantity.
-- 17. Find the top 10 products by revenue.
-- 18. Calculate average order value.
-- 19. Calculate total revenue by country.
-- 20. Find how many customers are from each country.
-- 21. Calculate average product price by category.
-- 22. Find categories generating more than $5,000 in revenue.
-- 23. Find the top 10 customers by total spending.
-- 24. Find customers who have never placed an order.
-- 25. Find customers who have placed more than 3 orders.
-- 26.Find the average amount spent per customer.
-- 27.Find the country with the highest total revenue.
-- 28.Which product generates the most revenue?
-- 29.Which category generates the most revenue?
-- 30.Which country generates the most revenue?
-- 31.Who is the most valuable customer?
-- 32.Which products have never been sold?
-- 33.Which products have less than 20 units in stock?
-- 34.Which products are both expensive and low-stock?
-- 35. What percentage of orders are cancelled?
-- 36.Find the customer who has spent the most money.
-- 37.Find the second-highest revenue-generating product.
-- 38.Find the best-selling product in each category.
-- 39.Find the country with the highest average order value.
-- 40.Find customers who have purchased products from at least 3 different categories.

-- 1. Show all customers
SELECT first_name,last_name FROM customers;

-- 2. Show all customers from canada
SELECT first_name, last_name, country
FROM customers
WHERE country="canada";

-- 3.Show all products costing more than $50 
SELECT product_name,price
FROM products
WHERE price>50;

-- 4.Show products in electronics category
SELECT product_name
FROM products 
WHERE category="electronics";

-- 5.Display the ten most expensive products
SELECT product_name,price
FROM products
ORDER BY price DESC
LIMIT 10;

-- 6.Show all completed orders
SELECT order_id  
FROM orders
WHERE status="completed";

-- 7.Show customers who signed up after January 1, 2025.
SELECT customer_id,first_name 
FROM customers
WHERE signup_date>"2025-01-01";

-- 8.Show each order with: customer name, order(id,date,status)
SELECT first_name, last_name, order_id, order_date, status
FROM orders
LEFT JOIN customers
  ON orders.customer_id=customers.customer_id;

-- 9. Show every product that has been ordered (product name, category, quantity ordered)
SELECT 
    p.product_name,
    p.category,
    SUM(oi.quantity) AS quantity_ordered
FROM products AS p
INNER JOIN order_item AS oi
    ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name, p.category;
  
-- 10. Show all customers and their orders, including customers who have never placed an order.
SELECT first_name, last_name, order_id
FROM customers
LEFT JOIN orders
  ON customers.customer_id=orders.customer_id;

-- 11. Show each order with :( customer name, product name, quantity, price) 
SELECT orders.order_id, first_name, last_name, product_name, quantity, price
FROM orders
LEFT JOIN customers
  ON orders.customer_id=customers.customer_id
LEFT JOIN order_item
  ON orders.order_id=order_item.order_id
LEFT JOIN products
  ON products.product_id=order_item.product_id;
  
-- 12. Calculate the revenue generated by each order item.
SELECT product_name, order_id, quantity*price AS revenue
FROM order_item
INNER JOIN products
  ON products.product_id=order_item.product_id;

-- 13. Calculate the total revenue generated by the store.
SELECT sum(quantity*price) AS total_revenue_store
FROM order_item
INNER JOIN products
  ON products.product_id=order_item.product_id;

-- 14. Calculate total revenue for each product.
SELECT product_name, sum(quantity*price) AS revenue
FROM order_item
INNER JOIN products
  ON products.product_id=order_item.product_id
GROUP BY product_name;
  
-- 15. Calculate total quantity sold for each product.
SELECT p.product_id, p.product_name, sum(quantity) 
FROM products AS p
INNER JOIN order_item AS oi
  ON p.product_id=oi.product_id
GROUP BY p.product_id,p.product_name;
  
-- 16. Find the top 10 best-selling products based on quantity.
SELECT product_name, sum(quantity) 
FROM products
INNER JOIN order_item
  ON products.product_id=order_item.product_id
GROUP BY product_name
ORDER BY sum(quantity) DESC
LIMIT 10;

-- 17. Find the top 10 products by revenue.
SELECT product_name, sum(quantity*price) AS revenue
FROM order_item
INNER JOIN products
  ON products.product_id=order_item.product_id
GROUP BY product_name
ORDER BY revenue DESC
LIMIT 10;

-- 18. Calculate average order value.
SELECT AVG(order_total) AS average_order_value
FROM(
   SELECT 
     order_item.order_id, sum(quantity*price) AS order_total
   FROM order_item
   INNER JOIN products
     ON order_item.product_id=products.product_id
   GROUP BY order_item.order_id
   ) AS order_total;
   
-- 19. Calculate total revenue by country.
SELECT country, SUM(quantity * price) AS revenue
FROM customers
LEFT JOIN orders
  ON orders.customer_id=customers.customer_id
LEFT JOIN order_item
  ON orders.order_id=order_item.order_id
LEFT JOIN products
  ON order_item.product_id=products.product_id
GROUP BY country;

-- 20. Find how many customers are from each country.
SELECT country, count(customer_id) AS total_customers
FROM customers
GROUP BY country;

-- 21. Calculate average product price by category.
SELECT category,AVG(price) AS average_price
FROM products
GROUP BY category;

-- 22. Find categories generating more than $5,000 in revenue.
SELECT p.category, SUM(oi.quantity * p.price) AS revenue
FROM products as p
INNER JOIN order_item AS oi
  ON p.product_id=oi.product_id
GROUP BY category
HAVING revenue>5000;

SELECT category, SUM(quantity * price) AS revenue
FROM products
LEFT JOIN order_item
  ON products.product_id=order_item.product_id
GROUP BY category
HAVING SUM(quantity*price)>5000;

-- 23. Find the top 10 customers by total spending.
SELECT first_name, last_name, SUM(price*quantity) AS money_spent
FROM customers AS c
LEFT JOIN orders AS o
  ON c.customer_id=o.customer_id
INNER JOIN order_item AS oi
  ON o.order_id=oi.order_id
INNER JOIN products as p
  ON oi.product_id=p.product_id
GROUP BY c.customer_id
ORDER BY money_spent DESC
LIMIT 10;

-- 24. Find customers who have never placed an order.
SELECT c.customer_id, c.first_name
FROM customers AS c
LEFT JOIN orders AS o
  ON c.customer_id=o.customer_id
WHERE o.order_id is null;

-- 25. Find customers who have placed more than 3 orders.
SELECT c.customer_id, c.first_name, count(o.order_id) as orders_placed
FROM customers AS c
LEFT JOIN orders AS o
  ON c.customer_id=o.customer_id
GROUP BY c.customer_id
HAVING orders_placed>3
ORDER BY orders_placed DESC;

-- 26.Find the average amount spent per customer.
SELECT customer_id, first_name,
    AVG(order_total) AS avg_spent_per_order
FROM (
    SELECT
        c.customer_id,
        c.first_name,
        o.order_id,
        SUM(p.price * oi.quantity) AS order_total
    FROM customers AS c
    JOIN orders AS o
        ON c.customer_id = o.customer_id
    JOIN order_item AS oi
        ON o.order_id = oi.order_id
    JOIN products AS p
        ON oi.product_id = p.product_id
    GROUP BY c.customer_id, c.first_name, o.order_id
) AS customer_orders
GROUP BY customer_id, first_name;

-- 27.Find the country with the highest total revenue.
SELECT country, SUM(quantity * price) AS revenue
FROM customers
LEFT JOIN orders
  ON orders.customer_id=customers.customer_id
LEFT JOIN order_item
  ON orders.order_id=order_item.order_id
LEFT JOIN products
  ON order_item.product_id=products.product_id
GROUP BY country
ORDER BY revenue DESC
LIMIT 1;

-- 28.Which product generates the most revenue?
SELECT products.product_id, products.product_name, SUM(price*quantity) AS revenue
FROM products
LEFT JOIN order_item
  ON order_item.product_id=products.product_id
GROUP BY products.product_id
ORDER BY revenue DESC
LIMIT 1;
  
-- 29.Which category generates the most revenue?
SELECT category, SUM(price*quantity) AS revenue
FROM products
LEFT JOIN order_item
  ON order_item.product_id=products.product_id
GROUP BY category
ORDER BY revenue DESC
LIMIT 1;

-- 30.Which country generates the most revenue?
SELECT country, SUM(price*quantity) AS revenue
FROM customers AS c
LEFT JOIN orders AS o
  ON c.customer_id=o.customer_id
LEFT JOIN order_item AS oi
  ON oi.order_id=o.order_id
LEFT JOIN products as p
  ON p.product_id=oi.product_id
GROUP BY country
ORDER BY revenue DESC
LIMIT 1;

-- 31.Who is the most valuable customer?
SELECT c.customer_id,c.first_name, c.last_name, SUM(price*quantity) AS revenue
FROM customers AS c
LEFT JOIN orders AS o
  ON c.customer_id=o.customer_id
LEFT JOIN order_item AS oi
  ON oi.order_id=o.order_id
LEFT JOIN products as p
  ON p.product_id=oi.product_id
GROUP BY c.customer_id
ORDER BY revenue DESC
LIMIT 1;

-- 32.Which products have never been sold?
SELECT p.product_id, p.product_name, oi.order_id
FROM products AS p
LEFT JOIN order_item AS oi
  ON p.product_id=oi.product_id
WHERE order_id IS NULL;

-- 33.Which products have less than 20 units in stock?
SELECT product_id, product_name, stock_quantity
FROM products
WHERE stock_quantity<20;

-- 34.Which products are both expensive and low-stock?
SELECT product_id, product_name, price, stock_quantity
FROM products
WHERE price > 100 AND stock_quantity < 20;

-- 35. What percentage of orders are cancelled?
SELECT SUM(status = 'cancelled') * 100.0 / COUNT(*) AS cancelled_percentage
FROM orders;

-- 36.Find the customer who has spent the most money.
SELECT c.customer_id, c.first_name, c.last_name, SUM(quantity*price) AS expenditure
FROM customers AS c
  LEFT JOIN orders AS o
  ON c.customer_id=o.customer_id
  LEFT JOIN order_item AS oi
  ON o.order_id=oi.order_id
  LEFT JOIN products AS p
  ON p.product_id=oi.product_id
ORDER BY expenditure DESC
LIMIT 1;

-- 37.Find the second-highest revenue-generating product.
SELECT p.product_id, product_name, SUM(quantity*price) AS revenue
FROM products as p
LEFT JOIN order_item as oi
 ON oi.product_id=p.product_id
 GROUP BY p.product_id,p.product_name
ORDER BY revenue DESC
LIMIT 1 OFFSET 1;

-- 38.Find the best-selling product in each category.
WITH product_sales AS (
    SELECT
        p.category,
        p.product_id,
        p.product_name,
        SUM(oi.quantity) AS total_sold
    FROM products AS p
    JOIN order_item AS oi
        ON p.product_id = oi.product_id
    GROUP BY p.category, p.product_id, p.product_name
),
ranked_products AS (
    SELECT
        category,
        product_name,
        total_sold,
        RANK() OVER (
            PARTITION BY category
            ORDER BY total_sold DESC
        ) AS product_rank
    FROM product_sales
)
SELECT
    category,
    product_name,
    total_sold
FROM ranked_products
WHERE product_rank = 1;

-- 39.Find the country with the highest average order value.
SELECT country, AVG(order_value) AS avg_order_value
FROM (
    SELECT
        c.country,
        o.order_id,
        SUM(p.price * oi.quantity) AS order_value
    FROM customers AS c
    JOIN orders AS o
        ON c.customer_id = o.customer_id
    JOIN order_item AS oi
        ON o.order_id = oi.order_id
    JOIN products AS p
        ON oi.product_id = p.product_id
	GROUP BY c.country,o.order_id
    ) AS country_order
    GROUP BY country
    ORDER BY avg_order_value DESC
    LIMIT 1;
  
-- 40.Find customers who have purchased products from at least 3 different categories.
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT p.category) AS categories_purchased
FROM customers AS c
JOIN orders AS o
    ON c.customer_id = o.customer_id
JOIN order_item AS oi
    ON o.order_id = oi.order_id
JOIN products AS p
    ON oi.product_id = p.product_id
GROUP BY c.customer_id, c.first_name, c.last_name
HAVING COUNT(DISTINCT p.category) >= 3;
